#pragma once
#include <memory>
#include <iostream>
#include <vector>
#include <fstream>
#include <string>
#include <cmath>
#include <limits>
#include "io.h"
#include "DeepLearning.pb.h"
#include "Util.h"
#include "Initializer.h"
#include "ActivationFunc.h"
#include "Layer.h"
#include "Layer_unitaryOp.h"
#include "Layer_binaryOp.h"
#include "Net.h"
#include <armadillo>
