// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeepLearning.proto

#ifndef PROTOBUF_DeepLearning_2eproto__INCLUDED
#define PROTOBUF_DeepLearning_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace DeepLearning {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_DeepLearning_2eproto();
void protobuf_AssignDesc_DeepLearning_2eproto();
void protobuf_ShutdownFile_DeepLearning_2eproto();

class NeuralNetParameter;
class LayerStructParameter;
class RNNStructParameter;
class NeuralNetTrainingParameter;

enum LayerStructParameter_ActivationType {
  LayerStructParameter_ActivationType_sigmoid = 1,
  LayerStructParameter_ActivationType_tanh = 2,
  LayerStructParameter_ActivationType_linear = 3,
  LayerStructParameter_ActivationType_softmax = 4
};
bool LayerStructParameter_ActivationType_IsValid(int value);
const LayerStructParameter_ActivationType LayerStructParameter_ActivationType_ActivationType_MIN = LayerStructParameter_ActivationType_sigmoid;
const LayerStructParameter_ActivationType LayerStructParameter_ActivationType_ActivationType_MAX = LayerStructParameter_ActivationType_softmax;
const int LayerStructParameter_ActivationType_ActivationType_ARRAYSIZE = LayerStructParameter_ActivationType_ActivationType_MAX + 1;

const ::google::protobuf::EnumDescriptor* LayerStructParameter_ActivationType_descriptor();
inline const ::std::string& LayerStructParameter_ActivationType_Name(LayerStructParameter_ActivationType value) {
  return ::google::protobuf::internal::NameOfEnum(
    LayerStructParameter_ActivationType_descriptor(), value);
}
inline bool LayerStructParameter_ActivationType_Parse(
    const ::std::string& name, LayerStructParameter_ActivationType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LayerStructParameter_ActivationType>(
    LayerStructParameter_ActivationType_descriptor(), name, value);
}
enum NeuralNetTrainingParameter_TrainerType {
  NeuralNetTrainingParameter_TrainerType_SGD = 1,
  NeuralNetTrainingParameter_TrainerType_iRProp = 2
};
bool NeuralNetTrainingParameter_TrainerType_IsValid(int value);
const NeuralNetTrainingParameter_TrainerType NeuralNetTrainingParameter_TrainerType_TrainerType_MIN = NeuralNetTrainingParameter_TrainerType_SGD;
const NeuralNetTrainingParameter_TrainerType NeuralNetTrainingParameter_TrainerType_TrainerType_MAX = NeuralNetTrainingParameter_TrainerType_iRProp;
const int NeuralNetTrainingParameter_TrainerType_TrainerType_ARRAYSIZE = NeuralNetTrainingParameter_TrainerType_TrainerType_MAX + 1;

const ::google::protobuf::EnumDescriptor* NeuralNetTrainingParameter_TrainerType_descriptor();
inline const ::std::string& NeuralNetTrainingParameter_TrainerType_Name(NeuralNetTrainingParameter_TrainerType value) {
  return ::google::protobuf::internal::NameOfEnum(
    NeuralNetTrainingParameter_TrainerType_descriptor(), value);
}
inline bool NeuralNetTrainingParameter_TrainerType_Parse(
    const ::std::string& name, NeuralNetTrainingParameter_TrainerType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NeuralNetTrainingParameter_TrainerType>(
    NeuralNetTrainingParameter_TrainerType_descriptor(), name, value);
}
// ===================================================================

class NeuralNetParameter : public ::google::protobuf::Message {
 public:
  NeuralNetParameter();
  virtual ~NeuralNetParameter();

  NeuralNetParameter(const NeuralNetParameter& from);

  inline NeuralNetParameter& operator=(const NeuralNetParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NeuralNetParameter& default_instance();

  void Swap(NeuralNetParameter* other);

  // implements Message ----------------------------------------------

  inline NeuralNetParameter* New() const { return New(NULL); }

  NeuralNetParameter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NeuralNetParameter& from);
  void MergeFrom(const NeuralNetParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NeuralNetParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // repeated .DeepLearning.LayerStructParameter layerStruct = 100;
  int layerstruct_size() const;
  void clear_layerstruct();
  static const int kLayerStructFieldNumber = 100;
  const ::DeepLearning::LayerStructParameter& layerstruct(int index) const;
  ::DeepLearning::LayerStructParameter* mutable_layerstruct(int index);
  ::DeepLearning::LayerStructParameter* add_layerstruct();
  const ::google::protobuf::RepeatedPtrField< ::DeepLearning::LayerStructParameter >&
      layerstruct() const;
  ::google::protobuf::RepeatedPtrField< ::DeepLearning::LayerStructParameter >*
      mutable_layerstruct();

  // optional .DeepLearning.NeuralNetTrainingParameter neuralNetTrainingParameter = 101;
  bool has_neuralnettrainingparameter() const;
  void clear_neuralnettrainingparameter();
  static const int kNeuralNetTrainingParameterFieldNumber = 101;
  const ::DeepLearning::NeuralNetTrainingParameter& neuralnettrainingparameter() const;
  ::DeepLearning::NeuralNetTrainingParameter* mutable_neuralnettrainingparameter();
  ::DeepLearning::NeuralNetTrainingParameter* release_neuralnettrainingparameter();
  void set_allocated_neuralnettrainingparameter(::DeepLearning::NeuralNetTrainingParameter* neuralnettrainingparameter);

  // optional .DeepLearning.RNNStructParameter rnnStruct = 102;
  bool has_rnnstruct() const;
  void clear_rnnstruct();
  static const int kRnnStructFieldNumber = 102;
  const ::DeepLearning::RNNStructParameter& rnnstruct() const;
  ::DeepLearning::RNNStructParameter* mutable_rnnstruct();
  ::DeepLearning::RNNStructParameter* release_rnnstruct();
  void set_allocated_rnnstruct(::DeepLearning::RNNStructParameter* rnnstruct);

  // @@protoc_insertion_point(class_scope:DeepLearning.NeuralNetParameter)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_neuralnettrainingparameter();
  inline void clear_has_neuralnettrainingparameter();
  inline void set_has_rnnstruct();
  inline void clear_has_rnnstruct();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::RepeatedPtrField< ::DeepLearning::LayerStructParameter > layerstruct_;
  ::DeepLearning::NeuralNetTrainingParameter* neuralnettrainingparameter_;
  ::DeepLearning::RNNStructParameter* rnnstruct_;
  friend void  protobuf_AddDesc_DeepLearning_2eproto();
  friend void protobuf_AssignDesc_DeepLearning_2eproto();
  friend void protobuf_ShutdownFile_DeepLearning_2eproto();

  void InitAsDefaultInstance();
  static NeuralNetParameter* default_instance_;
};
// -------------------------------------------------------------------

class LayerStructParameter : public ::google::protobuf::Message {
 public:
  LayerStructParameter();
  virtual ~LayerStructParameter();

  LayerStructParameter(const LayerStructParameter& from);

  inline LayerStructParameter& operator=(const LayerStructParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LayerStructParameter& default_instance();

  void Swap(LayerStructParameter* other);

  // implements Message ----------------------------------------------

  inline LayerStructParameter* New() const { return New(NULL); }

  LayerStructParameter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LayerStructParameter& from);
  void MergeFrom(const LayerStructParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LayerStructParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LayerStructParameter_ActivationType ActivationType;
  static const ActivationType sigmoid = LayerStructParameter_ActivationType_sigmoid;
  static const ActivationType tanh = LayerStructParameter_ActivationType_tanh;
  static const ActivationType linear = LayerStructParameter_ActivationType_linear;
  static const ActivationType softmax = LayerStructParameter_ActivationType_softmax;
  static inline bool ActivationType_IsValid(int value) {
    return LayerStructParameter_ActivationType_IsValid(value);
  }
  static const ActivationType ActivationType_MIN =
    LayerStructParameter_ActivationType_ActivationType_MIN;
  static const ActivationType ActivationType_MAX =
    LayerStructParameter_ActivationType_ActivationType_MAX;
  static const int ActivationType_ARRAYSIZE =
    LayerStructParameter_ActivationType_ActivationType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ActivationType_descriptor() {
    return LayerStructParameter_ActivationType_descriptor();
  }
  static inline const ::std::string& ActivationType_Name(ActivationType value) {
    return LayerStructParameter_ActivationType_Name(value);
  }
  static inline bool ActivationType_Parse(const ::std::string& name,
      ActivationType* value) {
    return LayerStructParameter_ActivationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional int32 inputDim = 1;
  bool has_inputdim() const;
  void clear_inputdim();
  static const int kInputDimFieldNumber = 1;
  ::google::protobuf::int32 inputdim() const;
  void set_inputdim(::google::protobuf::int32 value);

  // optional int32 outputDim = 2;
  bool has_outputdim() const;
  void clear_outputdim();
  static const int kOutputDimFieldNumber = 2;
  ::google::protobuf::int32 outputdim() const;
  void set_outputdim(::google::protobuf::int32 value);

  // optional .DeepLearning.LayerStructParameter.ActivationType activationType = 3;
  bool has_activationtype() const;
  void clear_activationtype();
  static const int kActivationTypeFieldNumber = 3;
  ::DeepLearning::LayerStructParameter_ActivationType activationtype() const;
  void set_activationtype(::DeepLearning::LayerStructParameter_ActivationType value);

  // optional string name = 4;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 4;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional string type = 5;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // @@protoc_insertion_point(class_scope:DeepLearning.LayerStructParameter)
 private:
  inline void set_has_inputdim();
  inline void clear_has_inputdim();
  inline void set_has_outputdim();
  inline void clear_has_outputdim();
  inline void set_has_activationtype();
  inline void clear_has_activationtype();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 inputdim_;
  ::google::protobuf::int32 outputdim_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  int activationtype_;
  friend void  protobuf_AddDesc_DeepLearning_2eproto();
  friend void protobuf_AssignDesc_DeepLearning_2eproto();
  friend void protobuf_ShutdownFile_DeepLearning_2eproto();

  void InitAsDefaultInstance();
  static LayerStructParameter* default_instance_;
};
// -------------------------------------------------------------------

class RNNStructParameter : public ::google::protobuf::Message {
 public:
  RNNStructParameter();
  virtual ~RNNStructParameter();

  RNNStructParameter(const RNNStructParameter& from);

  inline RNNStructParameter& operator=(const RNNStructParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RNNStructParameter& default_instance();

  void Swap(RNNStructParameter* other);

  // implements Message ----------------------------------------------

  inline RNNStructParameter* New() const { return New(NULL); }

  RNNStructParameter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RNNStructParameter& from);
  void MergeFrom(const RNNStructParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RNNStructParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 numHiddenLayers = 1;
  bool has_numhiddenlayers() const;
  void clear_numhiddenlayers();
  static const int kNumHiddenLayersFieldNumber = 1;
  ::google::protobuf::int32 numhiddenlayers() const;
  void set_numhiddenlayers(::google::protobuf::int32 value);

  // optional int32 hiddenLayerInputDim = 2;
  bool has_hiddenlayerinputdim() const;
  void clear_hiddenlayerinputdim();
  static const int kHiddenLayerInputDimFieldNumber = 2;
  ::google::protobuf::int32 hiddenlayerinputdim() const;
  void set_hiddenlayerinputdim(::google::protobuf::int32 value);

  // optional int32 hiddenLayerOutputDim = 3;
  bool has_hiddenlayeroutputdim() const;
  void clear_hiddenlayeroutputdim();
  static const int kHiddenLayerOutputDimFieldNumber = 3;
  ::google::protobuf::int32 hiddenlayeroutputdim() const;
  void set_hiddenlayeroutputdim(::google::protobuf::int32 value);

  // optional int32 inputDim = 4;
  bool has_inputdim() const;
  void clear_inputdim();
  static const int kInputDimFieldNumber = 4;
  ::google::protobuf::int32 inputdim() const;
  void set_inputdim(::google::protobuf::int32 value);

  // optional int32 outputDim = 5;
  bool has_outputdim() const;
  void clear_outputdim();
  static const int kOutputDimFieldNumber = 5;
  ::google::protobuf::int32 outputdim() const;
  void set_outputdim(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DeepLearning.RNNStructParameter)
 private:
  inline void set_has_numhiddenlayers();
  inline void clear_has_numhiddenlayers();
  inline void set_has_hiddenlayerinputdim();
  inline void clear_has_hiddenlayerinputdim();
  inline void set_has_hiddenlayeroutputdim();
  inline void clear_has_hiddenlayeroutputdim();
  inline void set_has_inputdim();
  inline void clear_has_inputdim();
  inline void set_has_outputdim();
  inline void clear_has_outputdim();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 numhiddenlayers_;
  ::google::protobuf::int32 hiddenlayerinputdim_;
  ::google::protobuf::int32 hiddenlayeroutputdim_;
  ::google::protobuf::int32 inputdim_;
  ::google::protobuf::int32 outputdim_;
  friend void  protobuf_AddDesc_DeepLearning_2eproto();
  friend void protobuf_AssignDesc_DeepLearning_2eproto();
  friend void protobuf_ShutdownFile_DeepLearning_2eproto();

  void InitAsDefaultInstance();
  static RNNStructParameter* default_instance_;
};
// -------------------------------------------------------------------

class NeuralNetTrainingParameter : public ::google::protobuf::Message {
 public:
  NeuralNetTrainingParameter();
  virtual ~NeuralNetTrainingParameter();

  NeuralNetTrainingParameter(const NeuralNetTrainingParameter& from);

  inline NeuralNetTrainingParameter& operator=(const NeuralNetTrainingParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NeuralNetTrainingParameter& default_instance();

  void Swap(NeuralNetTrainingParameter* other);

  // implements Message ----------------------------------------------

  inline NeuralNetTrainingParameter* New() const { return New(NULL); }

  NeuralNetTrainingParameter* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NeuralNetTrainingParameter& from);
  void MergeFrom(const NeuralNetTrainingParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NeuralNetTrainingParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef NeuralNetTrainingParameter_TrainerType TrainerType;
  static const TrainerType SGD = NeuralNetTrainingParameter_TrainerType_SGD;
  static const TrainerType iRProp = NeuralNetTrainingParameter_TrainerType_iRProp;
  static inline bool TrainerType_IsValid(int value) {
    return NeuralNetTrainingParameter_TrainerType_IsValid(value);
  }
  static const TrainerType TrainerType_MIN =
    NeuralNetTrainingParameter_TrainerType_TrainerType_MIN;
  static const TrainerType TrainerType_MAX =
    NeuralNetTrainingParameter_TrainerType_TrainerType_MAX;
  static const int TrainerType_ARRAYSIZE =
    NeuralNetTrainingParameter_TrainerType_TrainerType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  TrainerType_descriptor() {
    return NeuralNetTrainingParameter_TrainerType_descriptor();
  }
  static inline const ::std::string& TrainerType_Name(TrainerType value) {
    return NeuralNetTrainingParameter_TrainerType_Name(value);
  }
  static inline bool TrainerType_Parse(const ::std::string& name,
      TrainerType* value) {
    return NeuralNetTrainingParameter_TrainerType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional double learningRate = 1;
  bool has_learningrate() const;
  void clear_learningrate();
  static const int kLearningRateFieldNumber = 1;
  double learningrate() const;
  void set_learningrate(double value);

  // optional int32 maxIter = 2;
  bool has_maxiter() const;
  void clear_maxiter();
  static const int kMaxIterFieldNumber = 2;
  ::google::protobuf::int32 maxiter() const;
  void set_maxiter(::google::protobuf::int32 value);

  // optional int32 miniBatchSize = 3;
  bool has_minibatchsize() const;
  void clear_minibatchsize();
  static const int kMiniBatchSizeFieldNumber = 3;
  ::google::protobuf::int32 minibatchsize() const;
  void set_minibatchsize(::google::protobuf::int32 value);

  // optional int32 NEpoch = 4;
  bool has_nepoch() const;
  void clear_nepoch();
  static const int kNEpochFieldNumber = 4;
  ::google::protobuf::int32 nepoch() const;
  void set_nepoch(::google::protobuf::int32 value);

  // optional double epi = 5 [default = 1e-06];
  bool has_epi() const;
  void clear_epi();
  static const int kEpiFieldNumber = 5;
  double epi() const;
  void set_epi(double value);

  // optional .DeepLearning.NeuralNetTrainingParameter.TrainerType trainerType = 6 [default = SGD];
  bool has_trainertype() const;
  void clear_trainertype();
  static const int kTrainerTypeFieldNumber = 6;
  ::DeepLearning::NeuralNetTrainingParameter_TrainerType trainertype() const;
  void set_trainertype(::DeepLearning::NeuralNetTrainingParameter_TrainerType value);

  // optional double decayRate = 7 [default = 10];
  bool has_decayrate() const;
  void clear_decayrate();
  static const int kDecayRateFieldNumber = 7;
  double decayrate() const;
  void set_decayrate(double value);

  // optional double momentum = 8 [default = 0.9];
  bool has_momentum() const;
  void clear_momentum();
  static const int kMomentumFieldNumber = 8;
  double momentum() const;
  void set_momentum(double value);

  // optional bool verbose = 9 [default = true];
  bool has_verbose() const;
  void clear_verbose();
  static const int kVerboseFieldNumber = 9;
  bool verbose() const;
  void set_verbose(bool value);

  // optional int32 printInfoFrequency = 10 [default = 1];
  bool has_printinfofrequency() const;
  void clear_printinfofrequency();
  static const int kPrintInfoFrequencyFieldNumber = 10;
  ::google::protobuf::int32 printinfofrequency() const;
  void set_printinfofrequency(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DeepLearning.NeuralNetTrainingParameter)
 private:
  inline void set_has_learningrate();
  inline void clear_has_learningrate();
  inline void set_has_maxiter();
  inline void clear_has_maxiter();
  inline void set_has_minibatchsize();
  inline void clear_has_minibatchsize();
  inline void set_has_nepoch();
  inline void clear_has_nepoch();
  inline void set_has_epi();
  inline void clear_has_epi();
  inline void set_has_trainertype();
  inline void clear_has_trainertype();
  inline void set_has_decayrate();
  inline void clear_has_decayrate();
  inline void set_has_momentum();
  inline void clear_has_momentum();
  inline void set_has_verbose();
  inline void clear_has_verbose();
  inline void set_has_printinfofrequency();
  inline void clear_has_printinfofrequency();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double learningrate_;
  ::google::protobuf::int32 maxiter_;
  ::google::protobuf::int32 minibatchsize_;
  double epi_;
  ::google::protobuf::int32 nepoch_;
  int trainertype_;
  double decayrate_;
  double momentum_;
  bool verbose_;
  ::google::protobuf::int32 printinfofrequency_;
  friend void  protobuf_AddDesc_DeepLearning_2eproto();
  friend void protobuf_AssignDesc_DeepLearning_2eproto();
  friend void protobuf_ShutdownFile_DeepLearning_2eproto();

  void InitAsDefaultInstance();
  static NeuralNetTrainingParameter* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// NeuralNetParameter

// optional string name = 1;
inline bool NeuralNetParameter::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NeuralNetParameter::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NeuralNetParameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NeuralNetParameter::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& NeuralNetParameter::name() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetParameter.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NeuralNetParameter::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetParameter.name)
}
inline void NeuralNetParameter::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeepLearning.NeuralNetParameter.name)
}
inline void NeuralNetParameter::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeepLearning.NeuralNetParameter.name)
}
inline ::std::string* NeuralNetParameter::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:DeepLearning.NeuralNetParameter.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NeuralNetParameter::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NeuralNetParameter::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DeepLearning.NeuralNetParameter.name)
}

// optional string type = 2;
inline bool NeuralNetParameter::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NeuralNetParameter::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NeuralNetParameter::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NeuralNetParameter::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& NeuralNetParameter::type() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetParameter.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NeuralNetParameter::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetParameter.type)
}
inline void NeuralNetParameter::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeepLearning.NeuralNetParameter.type)
}
inline void NeuralNetParameter::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeepLearning.NeuralNetParameter.type)
}
inline ::std::string* NeuralNetParameter::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:DeepLearning.NeuralNetParameter.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NeuralNetParameter::release_type() {
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NeuralNetParameter::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:DeepLearning.NeuralNetParameter.type)
}

// repeated .DeepLearning.LayerStructParameter layerStruct = 100;
inline int NeuralNetParameter::layerstruct_size() const {
  return layerstruct_.size();
}
inline void NeuralNetParameter::clear_layerstruct() {
  layerstruct_.Clear();
}
inline const ::DeepLearning::LayerStructParameter& NeuralNetParameter::layerstruct(int index) const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetParameter.layerStruct)
  return layerstruct_.Get(index);
}
inline ::DeepLearning::LayerStructParameter* NeuralNetParameter::mutable_layerstruct(int index) {
  // @@protoc_insertion_point(field_mutable:DeepLearning.NeuralNetParameter.layerStruct)
  return layerstruct_.Mutable(index);
}
inline ::DeepLearning::LayerStructParameter* NeuralNetParameter::add_layerstruct() {
  // @@protoc_insertion_point(field_add:DeepLearning.NeuralNetParameter.layerStruct)
  return layerstruct_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::DeepLearning::LayerStructParameter >&
NeuralNetParameter::layerstruct() const {
  // @@protoc_insertion_point(field_list:DeepLearning.NeuralNetParameter.layerStruct)
  return layerstruct_;
}
inline ::google::protobuf::RepeatedPtrField< ::DeepLearning::LayerStructParameter >*
NeuralNetParameter::mutable_layerstruct() {
  // @@protoc_insertion_point(field_mutable_list:DeepLearning.NeuralNetParameter.layerStruct)
  return &layerstruct_;
}

// optional .DeepLearning.NeuralNetTrainingParameter neuralNetTrainingParameter = 101;
inline bool NeuralNetParameter::has_neuralnettrainingparameter() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NeuralNetParameter::set_has_neuralnettrainingparameter() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NeuralNetParameter::clear_has_neuralnettrainingparameter() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NeuralNetParameter::clear_neuralnettrainingparameter() {
  if (neuralnettrainingparameter_ != NULL) neuralnettrainingparameter_->::DeepLearning::NeuralNetTrainingParameter::Clear();
  clear_has_neuralnettrainingparameter();
}
inline const ::DeepLearning::NeuralNetTrainingParameter& NeuralNetParameter::neuralnettrainingparameter() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetParameter.neuralNetTrainingParameter)
  return neuralnettrainingparameter_ != NULL ? *neuralnettrainingparameter_ : *default_instance_->neuralnettrainingparameter_;
}
inline ::DeepLearning::NeuralNetTrainingParameter* NeuralNetParameter::mutable_neuralnettrainingparameter() {
  set_has_neuralnettrainingparameter();
  if (neuralnettrainingparameter_ == NULL) {
    neuralnettrainingparameter_ = new ::DeepLearning::NeuralNetTrainingParameter;
  }
  // @@protoc_insertion_point(field_mutable:DeepLearning.NeuralNetParameter.neuralNetTrainingParameter)
  return neuralnettrainingparameter_;
}
inline ::DeepLearning::NeuralNetTrainingParameter* NeuralNetParameter::release_neuralnettrainingparameter() {
  clear_has_neuralnettrainingparameter();
  ::DeepLearning::NeuralNetTrainingParameter* temp = neuralnettrainingparameter_;
  neuralnettrainingparameter_ = NULL;
  return temp;
}
inline void NeuralNetParameter::set_allocated_neuralnettrainingparameter(::DeepLearning::NeuralNetTrainingParameter* neuralnettrainingparameter) {
  delete neuralnettrainingparameter_;
  neuralnettrainingparameter_ = neuralnettrainingparameter;
  if (neuralnettrainingparameter) {
    set_has_neuralnettrainingparameter();
  } else {
    clear_has_neuralnettrainingparameter();
  }
  // @@protoc_insertion_point(field_set_allocated:DeepLearning.NeuralNetParameter.neuralNetTrainingParameter)
}

// optional .DeepLearning.RNNStructParameter rnnStruct = 102;
inline bool NeuralNetParameter::has_rnnstruct() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NeuralNetParameter::set_has_rnnstruct() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NeuralNetParameter::clear_has_rnnstruct() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NeuralNetParameter::clear_rnnstruct() {
  if (rnnstruct_ != NULL) rnnstruct_->::DeepLearning::RNNStructParameter::Clear();
  clear_has_rnnstruct();
}
inline const ::DeepLearning::RNNStructParameter& NeuralNetParameter::rnnstruct() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetParameter.rnnStruct)
  return rnnstruct_ != NULL ? *rnnstruct_ : *default_instance_->rnnstruct_;
}
inline ::DeepLearning::RNNStructParameter* NeuralNetParameter::mutable_rnnstruct() {
  set_has_rnnstruct();
  if (rnnstruct_ == NULL) {
    rnnstruct_ = new ::DeepLearning::RNNStructParameter;
  }
  // @@protoc_insertion_point(field_mutable:DeepLearning.NeuralNetParameter.rnnStruct)
  return rnnstruct_;
}
inline ::DeepLearning::RNNStructParameter* NeuralNetParameter::release_rnnstruct() {
  clear_has_rnnstruct();
  ::DeepLearning::RNNStructParameter* temp = rnnstruct_;
  rnnstruct_ = NULL;
  return temp;
}
inline void NeuralNetParameter::set_allocated_rnnstruct(::DeepLearning::RNNStructParameter* rnnstruct) {
  delete rnnstruct_;
  rnnstruct_ = rnnstruct;
  if (rnnstruct) {
    set_has_rnnstruct();
  } else {
    clear_has_rnnstruct();
  }
  // @@protoc_insertion_point(field_set_allocated:DeepLearning.NeuralNetParameter.rnnStruct)
}

// -------------------------------------------------------------------

// LayerStructParameter

// optional int32 inputDim = 1;
inline bool LayerStructParameter::has_inputdim() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LayerStructParameter::set_has_inputdim() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LayerStructParameter::clear_has_inputdim() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LayerStructParameter::clear_inputdim() {
  inputdim_ = 0;
  clear_has_inputdim();
}
inline ::google::protobuf::int32 LayerStructParameter::inputdim() const {
  // @@protoc_insertion_point(field_get:DeepLearning.LayerStructParameter.inputDim)
  return inputdim_;
}
inline void LayerStructParameter::set_inputdim(::google::protobuf::int32 value) {
  set_has_inputdim();
  inputdim_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.LayerStructParameter.inputDim)
}

// optional int32 outputDim = 2;
inline bool LayerStructParameter::has_outputdim() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LayerStructParameter::set_has_outputdim() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LayerStructParameter::clear_has_outputdim() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LayerStructParameter::clear_outputdim() {
  outputdim_ = 0;
  clear_has_outputdim();
}
inline ::google::protobuf::int32 LayerStructParameter::outputdim() const {
  // @@protoc_insertion_point(field_get:DeepLearning.LayerStructParameter.outputDim)
  return outputdim_;
}
inline void LayerStructParameter::set_outputdim(::google::protobuf::int32 value) {
  set_has_outputdim();
  outputdim_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.LayerStructParameter.outputDim)
}

// optional .DeepLearning.LayerStructParameter.ActivationType activationType = 3;
inline bool LayerStructParameter::has_activationtype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LayerStructParameter::set_has_activationtype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LayerStructParameter::clear_has_activationtype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LayerStructParameter::clear_activationtype() {
  activationtype_ = 1;
  clear_has_activationtype();
}
inline ::DeepLearning::LayerStructParameter_ActivationType LayerStructParameter::activationtype() const {
  // @@protoc_insertion_point(field_get:DeepLearning.LayerStructParameter.activationType)
  return static_cast< ::DeepLearning::LayerStructParameter_ActivationType >(activationtype_);
}
inline void LayerStructParameter::set_activationtype(::DeepLearning::LayerStructParameter_ActivationType value) {
  assert(::DeepLearning::LayerStructParameter_ActivationType_IsValid(value));
  set_has_activationtype();
  activationtype_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.LayerStructParameter.activationType)
}

// optional string name = 4;
inline bool LayerStructParameter::has_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LayerStructParameter::set_has_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LayerStructParameter::clear_has_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LayerStructParameter::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& LayerStructParameter::name() const {
  // @@protoc_insertion_point(field_get:DeepLearning.LayerStructParameter.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LayerStructParameter::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeepLearning.LayerStructParameter.name)
}
inline void LayerStructParameter::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeepLearning.LayerStructParameter.name)
}
inline void LayerStructParameter::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeepLearning.LayerStructParameter.name)
}
inline ::std::string* LayerStructParameter::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:DeepLearning.LayerStructParameter.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LayerStructParameter::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LayerStructParameter::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DeepLearning.LayerStructParameter.name)
}

// optional string type = 5;
inline bool LayerStructParameter::has_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LayerStructParameter::set_has_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LayerStructParameter::clear_has_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LayerStructParameter::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& LayerStructParameter::type() const {
  // @@protoc_insertion_point(field_get:DeepLearning.LayerStructParameter.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LayerStructParameter::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DeepLearning.LayerStructParameter.type)
}
inline void LayerStructParameter::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DeepLearning.LayerStructParameter.type)
}
inline void LayerStructParameter::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DeepLearning.LayerStructParameter.type)
}
inline ::std::string* LayerStructParameter::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:DeepLearning.LayerStructParameter.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LayerStructParameter::release_type() {
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LayerStructParameter::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:DeepLearning.LayerStructParameter.type)
}

// -------------------------------------------------------------------

// RNNStructParameter

// optional int32 numHiddenLayers = 1;
inline bool RNNStructParameter::has_numhiddenlayers() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RNNStructParameter::set_has_numhiddenlayers() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RNNStructParameter::clear_has_numhiddenlayers() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RNNStructParameter::clear_numhiddenlayers() {
  numhiddenlayers_ = 0;
  clear_has_numhiddenlayers();
}
inline ::google::protobuf::int32 RNNStructParameter::numhiddenlayers() const {
  // @@protoc_insertion_point(field_get:DeepLearning.RNNStructParameter.numHiddenLayers)
  return numhiddenlayers_;
}
inline void RNNStructParameter::set_numhiddenlayers(::google::protobuf::int32 value) {
  set_has_numhiddenlayers();
  numhiddenlayers_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.RNNStructParameter.numHiddenLayers)
}

// optional int32 hiddenLayerInputDim = 2;
inline bool RNNStructParameter::has_hiddenlayerinputdim() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RNNStructParameter::set_has_hiddenlayerinputdim() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RNNStructParameter::clear_has_hiddenlayerinputdim() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RNNStructParameter::clear_hiddenlayerinputdim() {
  hiddenlayerinputdim_ = 0;
  clear_has_hiddenlayerinputdim();
}
inline ::google::protobuf::int32 RNNStructParameter::hiddenlayerinputdim() const {
  // @@protoc_insertion_point(field_get:DeepLearning.RNNStructParameter.hiddenLayerInputDim)
  return hiddenlayerinputdim_;
}
inline void RNNStructParameter::set_hiddenlayerinputdim(::google::protobuf::int32 value) {
  set_has_hiddenlayerinputdim();
  hiddenlayerinputdim_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.RNNStructParameter.hiddenLayerInputDim)
}

// optional int32 hiddenLayerOutputDim = 3;
inline bool RNNStructParameter::has_hiddenlayeroutputdim() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RNNStructParameter::set_has_hiddenlayeroutputdim() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RNNStructParameter::clear_has_hiddenlayeroutputdim() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RNNStructParameter::clear_hiddenlayeroutputdim() {
  hiddenlayeroutputdim_ = 0;
  clear_has_hiddenlayeroutputdim();
}
inline ::google::protobuf::int32 RNNStructParameter::hiddenlayeroutputdim() const {
  // @@protoc_insertion_point(field_get:DeepLearning.RNNStructParameter.hiddenLayerOutputDim)
  return hiddenlayeroutputdim_;
}
inline void RNNStructParameter::set_hiddenlayeroutputdim(::google::protobuf::int32 value) {
  set_has_hiddenlayeroutputdim();
  hiddenlayeroutputdim_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.RNNStructParameter.hiddenLayerOutputDim)
}

// optional int32 inputDim = 4;
inline bool RNNStructParameter::has_inputdim() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RNNStructParameter::set_has_inputdim() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RNNStructParameter::clear_has_inputdim() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RNNStructParameter::clear_inputdim() {
  inputdim_ = 0;
  clear_has_inputdim();
}
inline ::google::protobuf::int32 RNNStructParameter::inputdim() const {
  // @@protoc_insertion_point(field_get:DeepLearning.RNNStructParameter.inputDim)
  return inputdim_;
}
inline void RNNStructParameter::set_inputdim(::google::protobuf::int32 value) {
  set_has_inputdim();
  inputdim_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.RNNStructParameter.inputDim)
}

// optional int32 outputDim = 5;
inline bool RNNStructParameter::has_outputdim() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RNNStructParameter::set_has_outputdim() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RNNStructParameter::clear_has_outputdim() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RNNStructParameter::clear_outputdim() {
  outputdim_ = 0;
  clear_has_outputdim();
}
inline ::google::protobuf::int32 RNNStructParameter::outputdim() const {
  // @@protoc_insertion_point(field_get:DeepLearning.RNNStructParameter.outputDim)
  return outputdim_;
}
inline void RNNStructParameter::set_outputdim(::google::protobuf::int32 value) {
  set_has_outputdim();
  outputdim_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.RNNStructParameter.outputDim)
}

// -------------------------------------------------------------------

// NeuralNetTrainingParameter

// optional double learningRate = 1;
inline bool NeuralNetTrainingParameter::has_learningrate() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_learningrate() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NeuralNetTrainingParameter::clear_has_learningrate() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NeuralNetTrainingParameter::clear_learningrate() {
  learningrate_ = 0;
  clear_has_learningrate();
}
inline double NeuralNetTrainingParameter::learningrate() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.learningRate)
  return learningrate_;
}
inline void NeuralNetTrainingParameter::set_learningrate(double value) {
  set_has_learningrate();
  learningrate_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.learningRate)
}

// optional int32 maxIter = 2;
inline bool NeuralNetTrainingParameter::has_maxiter() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_maxiter() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NeuralNetTrainingParameter::clear_has_maxiter() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NeuralNetTrainingParameter::clear_maxiter() {
  maxiter_ = 0;
  clear_has_maxiter();
}
inline ::google::protobuf::int32 NeuralNetTrainingParameter::maxiter() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.maxIter)
  return maxiter_;
}
inline void NeuralNetTrainingParameter::set_maxiter(::google::protobuf::int32 value) {
  set_has_maxiter();
  maxiter_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.maxIter)
}

// optional int32 miniBatchSize = 3;
inline bool NeuralNetTrainingParameter::has_minibatchsize() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_minibatchsize() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NeuralNetTrainingParameter::clear_has_minibatchsize() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NeuralNetTrainingParameter::clear_minibatchsize() {
  minibatchsize_ = 0;
  clear_has_minibatchsize();
}
inline ::google::protobuf::int32 NeuralNetTrainingParameter::minibatchsize() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.miniBatchSize)
  return minibatchsize_;
}
inline void NeuralNetTrainingParameter::set_minibatchsize(::google::protobuf::int32 value) {
  set_has_minibatchsize();
  minibatchsize_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.miniBatchSize)
}

// optional int32 NEpoch = 4;
inline bool NeuralNetTrainingParameter::has_nepoch() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_nepoch() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NeuralNetTrainingParameter::clear_has_nepoch() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NeuralNetTrainingParameter::clear_nepoch() {
  nepoch_ = 0;
  clear_has_nepoch();
}
inline ::google::protobuf::int32 NeuralNetTrainingParameter::nepoch() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.NEpoch)
  return nepoch_;
}
inline void NeuralNetTrainingParameter::set_nepoch(::google::protobuf::int32 value) {
  set_has_nepoch();
  nepoch_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.NEpoch)
}

// optional double epi = 5 [default = 1e-06];
inline bool NeuralNetTrainingParameter::has_epi() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_epi() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NeuralNetTrainingParameter::clear_has_epi() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NeuralNetTrainingParameter::clear_epi() {
  epi_ = 1e-06;
  clear_has_epi();
}
inline double NeuralNetTrainingParameter::epi() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.epi)
  return epi_;
}
inline void NeuralNetTrainingParameter::set_epi(double value) {
  set_has_epi();
  epi_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.epi)
}

// optional .DeepLearning.NeuralNetTrainingParameter.TrainerType trainerType = 6 [default = SGD];
inline bool NeuralNetTrainingParameter::has_trainertype() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_trainertype() {
  _has_bits_[0] |= 0x00000020u;
}
inline void NeuralNetTrainingParameter::clear_has_trainertype() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void NeuralNetTrainingParameter::clear_trainertype() {
  trainertype_ = 1;
  clear_has_trainertype();
}
inline ::DeepLearning::NeuralNetTrainingParameter_TrainerType NeuralNetTrainingParameter::trainertype() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.trainerType)
  return static_cast< ::DeepLearning::NeuralNetTrainingParameter_TrainerType >(trainertype_);
}
inline void NeuralNetTrainingParameter::set_trainertype(::DeepLearning::NeuralNetTrainingParameter_TrainerType value) {
  assert(::DeepLearning::NeuralNetTrainingParameter_TrainerType_IsValid(value));
  set_has_trainertype();
  trainertype_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.trainerType)
}

// optional double decayRate = 7 [default = 10];
inline bool NeuralNetTrainingParameter::has_decayrate() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_decayrate() {
  _has_bits_[0] |= 0x00000040u;
}
inline void NeuralNetTrainingParameter::clear_has_decayrate() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void NeuralNetTrainingParameter::clear_decayrate() {
  decayrate_ = 10;
  clear_has_decayrate();
}
inline double NeuralNetTrainingParameter::decayrate() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.decayRate)
  return decayrate_;
}
inline void NeuralNetTrainingParameter::set_decayrate(double value) {
  set_has_decayrate();
  decayrate_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.decayRate)
}

// optional double momentum = 8 [default = 0.9];
inline bool NeuralNetTrainingParameter::has_momentum() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_momentum() {
  _has_bits_[0] |= 0x00000080u;
}
inline void NeuralNetTrainingParameter::clear_has_momentum() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void NeuralNetTrainingParameter::clear_momentum() {
  momentum_ = 0.9;
  clear_has_momentum();
}
inline double NeuralNetTrainingParameter::momentum() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.momentum)
  return momentum_;
}
inline void NeuralNetTrainingParameter::set_momentum(double value) {
  set_has_momentum();
  momentum_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.momentum)
}

// optional bool verbose = 9 [default = true];
inline bool NeuralNetTrainingParameter::has_verbose() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_verbose() {
  _has_bits_[0] |= 0x00000100u;
}
inline void NeuralNetTrainingParameter::clear_has_verbose() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void NeuralNetTrainingParameter::clear_verbose() {
  verbose_ = true;
  clear_has_verbose();
}
inline bool NeuralNetTrainingParameter::verbose() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.verbose)
  return verbose_;
}
inline void NeuralNetTrainingParameter::set_verbose(bool value) {
  set_has_verbose();
  verbose_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.verbose)
}

// optional int32 printInfoFrequency = 10 [default = 1];
inline bool NeuralNetTrainingParameter::has_printinfofrequency() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void NeuralNetTrainingParameter::set_has_printinfofrequency() {
  _has_bits_[0] |= 0x00000200u;
}
inline void NeuralNetTrainingParameter::clear_has_printinfofrequency() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void NeuralNetTrainingParameter::clear_printinfofrequency() {
  printinfofrequency_ = 1;
  clear_has_printinfofrequency();
}
inline ::google::protobuf::int32 NeuralNetTrainingParameter::printinfofrequency() const {
  // @@protoc_insertion_point(field_get:DeepLearning.NeuralNetTrainingParameter.printInfoFrequency)
  return printinfofrequency_;
}
inline void NeuralNetTrainingParameter::set_printinfofrequency(::google::protobuf::int32 value) {
  set_has_printinfofrequency();
  printinfofrequency_ = value;
  // @@protoc_insertion_point(field_set:DeepLearning.NeuralNetTrainingParameter.printInfoFrequency)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DeepLearning

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::DeepLearning::LayerStructParameter_ActivationType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DeepLearning::LayerStructParameter_ActivationType>() {
  return ::DeepLearning::LayerStructParameter_ActivationType_descriptor();
}
template <> struct is_proto_enum< ::DeepLearning::NeuralNetTrainingParameter_TrainerType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DeepLearning::NeuralNetTrainingParameter_TrainerType>() {
  return ::DeepLearning::NeuralNetTrainingParameter_TrainerType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_DeepLearning_2eproto__INCLUDED
